### ISSUE TITLE
No it's not Starter edition compatiable

### ISSUE THREAD

**Issue by zhankezk** [MichaelJames6/My-StepCounter#14]
Just want to point out, it fails to build on Mac Starter Edition of Xamarin due to project size too large. Please remove that statement.

**Comment by jermaine150** [comment]
I have the same issue. Downloaded the sample and get the following error on build: "you are using 147 features which require Xamarion.IOS Indie ...."

**Comment by MikeCodesDotNET** [comment]
Confirmed. It looks like adding Xamarin.Insights causes the issue. I'm going to leave this open for a little as I don't think I need to fix this right now.

**Comment by MikeCodesDotNET** [comment]
No need to fix as starter is dead and Xamarin is free.
